name: Emily Winsauer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9361803669016808
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#03030d'
    - '#223232'
    - '#63533c'
    - '#a3b0a7'
    - '#f8ead0'
  brandStrength: 0.5
  lightness: 0.28936241031624377
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
