typography_spectrum: 0.32619
color:
  brandColors:
    - '#03030d'
    - '#223232'
    - '#63533c'
    - '#a3b0a7'
    - '#f8ead0'
  brandStrength: 0.5
  lightness: 0.28936241031624377
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Emily Winsauer
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Emily Winsauer | Writer
description: Stay Curious
purpose: []
